service: serverless-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
	planet:
		handler: sw.planets
		events:
		- httpApi:
			path: /sw/planets/{ID}
			method: get
			cors: true
	specie:
		handler: sw.species
		events:
		- httpApi:
			path: /sw/species/{ID}
			method: get
			cors: true
	ucreate:
		handler: user.save
		events:
		- httpApi:
			path: /u/
			method: post
			cors: true
	ulist:
		handler: user.list
		events:
		- httpApi:
			path: /u/{ID}
			method: get
			cors: true